server:
  port: 8280
  context-path: /portal

security:
  basic:
    enabled: true
  cas:
    enabled: true
    server:
      base-url: https://rnodev-passport.hgicreate.com/cas
    service:
      resolution-mode: dynamic
    user:
      roles-attributes: roles

management:
  security:
    enabled: false

logging:
  level:
    com.hgicreate.rno: info

spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.50.20:1521:rnodb
    username: rno4dev
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: false
    properties:
      hibernate.format_sql: true
  http:
    multipart:
      max-file-size: 900MB
      max-request-size: 900MB

rno:
  app-code: rno-tdlte
  check-url-prefix: false
  path:
    upload-files: /tmp/rno-cloud-platform/uploads
  ftp:
    host: 192.168.9.11
    port: 21
    username: rnoftp
    password: rnodev
    remote-path: /var/rno/data

mybatis:
  configuration:
    map-underscore-to-camel-case: true
